"""song.youtube_id

Revision ID: 66ecebf91fa5
Revises: 875426697aba
Create Date: 2026-08-29 20:40:53.115625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ecebf91fa5'
down_revision: Union[str, Sequence[str], None] = '875426697aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('youtube_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('song_youtube_id_idx'), 'song', ['youtube_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('song_youtube_id_idx'), table_name='song')
    op.drop_column('song', 'youtube_id')
    # ### end Alembic commands ###
