"""playlists, likes, refresh tokens

Revision ID: 875426697aba
Revises: 514c9d36b3ee
Create Date: 2026-08-28 14:18:57.510945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875426697aba'
down_revision: Union[str, Sequence[str], None] = '514c9d36b3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_songs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('song_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name=op.f('liked_songs_song_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('liked_songs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'song_id', name=op.f('liked_songs_pkey'))
    )
    op.create_table('playlist',
    sa.Column('playlist_name', sa.String(length=50), nullable=False),
    sa.Column('playlist_duration', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('playlist_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('playlist_pkey'))
    )
    op.create_index(op.f('playlist_playlist_name_idx'), 'playlist', ['playlist_name'], unique=False)
    op.create_table('refresh_token',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_with_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['replaced_with_id'], ['refresh_token.id'], name=op.f('refresh_token_replaced_with_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('refresh_token_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_token_pkey'))
    )
    op.create_index(op.f('refresh_token_expires_at_idx'), 'refresh_token', ['expires_at'], unique=False)
    op.create_index(op.f('refresh_token_family_id_idx'), 'refresh_token', ['family_id'], unique=False)
    op.create_index(op.f('refresh_token_token_hash_idx'), 'refresh_token', ['token_hash'], unique=True)
    op.create_index(op.f('refresh_token_user_id_idx'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('playlist_song',
    sa.Column('playlist_id', sa.Uuid(), nullable=False),
    sa.Column('song_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name=op.f('playlist_song_playlist_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name=op.f('playlist_song_song_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id', name=op.f('playlist_song_pkey'))
    )
    op.create_index('idx_song_created_at_id', 'song', ['created_at', 'id'], unique=False)
    op.add_column('user', sa.Column('verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verified')
    op.drop_index('idx_song_created_at_id', table_name='song')
    op.drop_table('playlist_song')
    op.drop_index(op.f('refresh_token_user_id_idx'), table_name='refresh_token')
    op.drop_index(op.f('refresh_token_token_hash_idx'), table_name='refresh_token')
    op.drop_index(op.f('refresh_token_family_id_idx'), table_name='refresh_token')
    op.drop_index(op.f('refresh_token_expires_at_idx'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('playlist_playlist_name_idx'), table_name='playlist')
    op.drop_table('playlist')
    op.drop_table('liked_songs')
    # ### end Alembic commands ###
